import { theme } from '../styles/theme';

export const homeStyles = {
  hero: {
    position: 'relative',
    minHeight: '50vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #6B46C1 0%, #805AD5 50%, #9F7AEA 100%)',
    color: 'white',
    overflow: 'hidden',
    padding: '2rem',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
    background: 'linear-gradient(135deg, rgba(155, 89, 182, 0.7) 0%, rgba(142, 68, 173, 0.7) 100%)',
    opacity: 1,
    pointerEvents: 'none',
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
    textAlign: 'center',
    maxWidth: '800px',
  },
  heroTitle: {
    fontSize: '3.5rem',
    fontWeight: '700',
    marginBottom: '1.5rem',
    background: 'linear-gradient(45deg, #fff, #E9D8FD)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  heroSubtitle: {
    fontSize: '1.25rem',
    lineHeight: '1.8',
    marginBottom: '2.5rem',
    opacity: 0.9,
  },
  heroButton: {
    padding: '1rem 2rem',
    fontSize: '1.1rem',
    fontWeight: '600',
    color: '#6B46C1',
    background: 'white',
    border: 'none',
    borderRadius: '50px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(107, 70, 193, 0.2)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 20px rgba(107, 70, 193, 0.3)',
      background: '#F7FAFC',
    },
  },
  sectionTitle: {
    fontSize: '2rem',
    fontWeight: '600',
    margin: '2rem 0 1rem',
    paddingLeft: '1rem',
  },
  carouselContainer: {
    padding: '1rem',
    marginBottom: '2rem',
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(15, 10, 26, 0.13)',
    borderRadius: '24px',
    boxShadow: '0 4px 24px rgba(72, 187, 120, 0.15), 0 4px 24px rgba(128, 90, 213, 0.15)',
    border: 'none'
  },
  songsSection: {
    marginTop: '3rem',
  },
  loading: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    fontSize: '1.2rem',
  },
  error: {
    color: 'red',
    textAlign: 'center',
    padding: '2rem',
    fontSize: '1.2rem',
  },
}; 